apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
  namespace: webhook
webhooks:
  - name: example-webhook.webhook.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    clientConfig:
      service:
        name: example-webhook
        namespace: webhook
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVVUxSL1I0UUxwNGFncXlyNGVlZ3RaVEtiLzl3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qUXdNVEUyCk1qQXlOVEF3V2hjTk1qa3dNVEUwTWpBeU5UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMNzU3MTByCmhrOWJIREkwVDF5a0hFMVVVQVJzbkNlaFVIbWZLOGdRa1NvS1dIOU9VcjlkZngxbER0N0tzUWpyV1REZEFZN1cKMHh1S3orWFNqanlCajB4aVJkNVhtWFcvbTUvdXpjelNlNVQ4NUV4SUUxZmhZdU5oOExKYjh6L3k5VTlNRjRHeQo1YWhHeWs2dFJJYlcxL21HS1Vwa295NzRxQTI0VkdLRW1ESFhrRkl4TzQ4ZlpRK29tdmpmeGxEQ25FZy9nWkVNClRjajhZcGxRNlF3WjA5TEliN09DUFdMM250NDhRdXYrMFNpa0UzWlNEd3RKQjRRM0hneEtSYVFZUlNXT0xNSDEKenQ4QW9uK2paUFYwWWptWk1SWXFrbUJZVUozN3hnK2gvMFZBYnJrbXlWT0lwYmNKUnNBTHV5UW5NdlF0U0pXcgp2LzFlREhEYU9id3R6Y2NDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkhNZ294bkp3N283VWNqdHBHWVV4U1MzWWI5ZU1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUEwUnY3S24yaHZZSlkwTkVBazUremVUeW9PVXEvbkJCbm4wN1hZeWE4cGxySnZpUnU2TzJGbApVUDZXUHAwM1haaTBGWWZJQXgySXV5dVZ6OEoxY0NyZGsyb2lHTDZSSEVYWjBZcXlObndkcTlwTk5ZODRGREFrCjk3TFJqSllqdW9OSnFyRVR6OUoySkNOY2JJOTZPeGtTVnAwcXNnZWJ1SmJjOEI5YU43ck5TbTB2N0Y4V0hwVlAKdmV4YUhiOEpYc1VGRGNrblBnbHB3OC9rM3hQcmZHZ2RqTWI1c0RTWUUxTWdLUG8vYURKTVZWS200TDBsQ1JwUApacTEvTWlpNUNrZ05XRU9EN2k2WkEzRUM1My9WVDZxQjVwbnJMS0VjcUh6SG5vWXlrcFl2bXBjTVFVRURYMzVnClAwbklLV2lhcFQvUng4ZXlQekQ5T0QxcmoydWFuV2ZjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]