apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    enable-deletion-protection: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: prod
  labels:
    "key1": "value1"
spec:
  containers:
  - name: nginx
    image: nginx
