apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-add-deletion-protection
webhooks:
  - name: mutating.webhook.k8s.com
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    namespaceSelector:
      matchLabels:
        enable-deletion-protection: "true"
    clientConfig:
      service:
        name: webhook
        namespace: webhook
        path: "/mutate"
      caBundle: "${CA_PEM_B64}"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
