apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-deletion-protection
webhooks:
  - name: validating.webhook.k8s.com
    sideEffects: None
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
       url: "https://192.168.11.80:8443/validate"
#      service:
#        name: example-webhook
#        namespace: webhook
#        path: "/validate"
       caBundle: "${CA_PEM_B64}"
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: 5
