apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-deletion-protection
webhooks:
  - name: validating.webhook.k8s.com
    sideEffects: None
    namespaceSelector:
      matchLabels:
        enable-deletion-protection: "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["DELETE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: webhook
        namespace: webhook
        path: "/validate"
      caBundle: "${CA_PEM_B64}"
    admissionReviewVersions: ["v1", "v1beta1"]
    timeoutSeconds: 5
