FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y wget git gcc

RUN wget -P /tmp "https://dl.google.com/go/go1.21.6.linux-amd64.tar.gz"

RUN tar -C /usr/local -xzf "/tmp/go1.21.6.linux-amd64.tar.gz"
RUN rm "/tmp/go1.21.6.linux-amd64.tar.gz"

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

COPY . /app/

WORKDIR /app

RUN go mod download

RUN CGO_ENABLED=0 go build -o /usr/local/bin/webhook

RUN chmod +x /usr/local/bin/webhook

ENTRYPOINT ["webhook"]